### ISSUE TITLE
[Task] Move virtual pods to SYS_NAMESPACE

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/aranya#30]
### Goal

Manage virtual pods and virtual pod roles in SYS_NAMESPACE

### ETA

none

### Sub-tasks

- [x] Update controller for virtual pods
- [x] Update rbac template in helm chart
- [x] Update virtual node pod controller

**Comment by jeffreystoke** [comment]
Done.
